import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import imageLoader from "../imageLoader";
import { ICharacters, IGetCharacterResults } from "../types/types";
import Layout from "../components/Layout";
import { ReactElement } from "react";

//character props'unu aldı, bu prop ICharacter type'a eşit [] bu array anlamına gelir.
const Characters: NextPage<{ characters: ICharacters[] }> = ({
  characters,
}) => {
  return (
    <div className="container">
      <Head>
        <title>Ricky and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {characters.map((items) => {
        return (
          <div key={items.id} className="main">
            <Link href={`/characters/${items.id}`}>
              <a>
                <h3> {items.name}</h3>
                <Image
                  loader={imageLoader} //image optimization için
                  unoptimized //true olunca kaynak görüntü olduğu gibi gelir (kalite, boyut).
                  src={items.image}
                  alt={items.name}
                  width="150"
                  height="150"
                  className="characterImage"
                />
              </a>
            </Link>
          </div>
        );
      })}

      <style jsx>{`
        .container {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          grid-gap: 1rem;
          margin: 1rem;
          padding: 1rem;
          border-radius: 5px;
          border: 1px solid #eaeaea;
          box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
        }
        
        .main {
          background-color: #f5f5f5;
          padding: 1rem;
          border-radius: 5px;
          border: 1px solid #eaeaea;
        }

        .main:hover {
          background-color: #eaeaea;
          cursor: pointer;
          color: #ff0000;
        }
      `}</style>
    </div>
  );
};

Characters.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

//getstaticProps kodun server side'da çalışmasını sağlar. Buradaki props'u da kullanacağımız func.'a veririz.
//sadece pages folder'da import edilir, diğer componentlerde import edilmez prop olarak verilir.
//buradaki context parametlere erişimi sağlar.
export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: IGetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Characters;
