import React from "react";
import Head from "next/head";
import Layout from "../components/Layout";
import { GetStaticProps } from "next";
import { IEpisodes } from "../types/types";
import styles from "../styles/Episodes.module.css";
import type { NextPageWithLayout } from "next";

const Episodes: NextPageWithLayout<{ episodes: IEpisodes[] }> = ({episodes}) => {
  return (
    // <div>{JSON.stringify(episodes)}</div>
    <div className={styles.container}>
      <Head>
        <title>Episodes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/episod.jpg" />
      </Head>

      {episodes.map((items) => {
        return (
          <div key={items.id} className={styles.content}>
            <h3>{items.name}</h3>
            <p>
              <img src="/timetable.png" alt="time" className={styles.icon} />
              {items.air_date}
            </p>
            <p>
              <img src="/chapter.png" alt="episode" className={styles.icon} />
              {items.episode}
            </p>
            <p>
              <img src="/create.png" alt="created" className={styles.icon} />
              {items.created}
            </p>
            {items.characters.map((item) => {
              return (
                <li key={item} className={styles.list}>
                  <img src="/check.png" alt="check" className={styles.icon} />
                  {item}
                </li>
              );
            })}
          </div>
        );
      })}
    </div>
  );
};

Episodes.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/episode");

  const { results } = await res.json();

  return {
    props: {
      episodes: results,
    },
  };
};

export default Episodes;
