import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ricky and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>
        <h1>Rick and Morty</h1>

        <div className={styles.pImg}>
          <span>
            <img src="/home.png" alt="home-img" />
          </span>

          <p>
            Pick your favorite character and find out more about them. <br />
            <br />
            Rick and Morty is an American adult animated science fiction sitcom
            created by Justin Roiland and Dan Harmon for Cartoon Network's
            nighttime programming block Adult Swim. The series follows the
            misadventures of cynical mad scientist Rick Sanchez and his
            good-hearted but fretful grandson Morty Smith, who split their time
            between domestic life and interdimensional adventures. Roiland
            voices the eponymous characters, with Chris Parnell, Spencer Grammer
            and Sarah Chalke voicing the rest of Rick and Morty's family. The
            series originated from an animated short parody film of Back to the
            Future, created by Roiland for Channel 101, a short-film festival
            co-founded by Harmon. Since its debut, the series has received
            critical acclaim for its originality, creativity and humor. They
            have won two Primetime Emmy Awards for Outstanding Animated Program.
            The fifth season premiered on June 20, 2021, and consisted of ten
            episodes. A sixth season was confirmed as part of a long-term deal
            in May 2018 that ordered 70 new episodes over an unspecified number
            of seasons. <a href="https://en.wikipedia.org/wiki/Rick_and_Morty"> More details...</a>
            <br /> <br />
            <Link href="/characters">
              <a>CHARACTERS CLICKS!</a>
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}

export default Home;
